apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-decision-point
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-559-10
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/policy-decision-point
    repoURL: {{ .Values.spec.repo }}
    targetRevision: {{ .Values.spec.targetRevision }}
    {{ if .Values.spec.helm.valueFiles }}
    helm:
      valueFiles:
        {{- range .Values.spec.helm.valueFiles }}
        - {{ . }}
        {{- end }}    
    {{ end }}
  {{- with .Values.spec.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}