apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-local
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test-559-10
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/s3-local
    repoURL: {{ .Values.spec.repo }}
    targetRevision: {{ .Values.spec.targetRevision }}
  {{- with .Values.spec.syncPolicy }}
  syncPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}